#!/usr/bin/env bash

# Copyright (c) 2021-2025 community-scripts ORG
# Author: [Your GitHub Username]
# License: MIT | https://github.com/community-scripts/ProxmoxVE/raw/main/LICENSE
# Source: https://projectzomboid.com/

source /dev/stdin <<< "$FUNCTIONS_FILE_PATH"

color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

msg_info "Installing Dependencies"
$STD apt-get install -y \
  curl \
  wget \
  sudo \
  mc \
  software-properties-common \
  apt-transport-https \
  ca-certificates \
  gnupg
msg_ok "Installed Dependencies"

msg_info "Enabling i386 Architecture"
$STD dpkg --add-architecture i386
$STD apt-get update
msg_ok "Enabled i386 Architecture"

msg_info "Installing 32-bit Libraries"
$STD apt-get install -y \
  lib32gcc-s1 \
  lib32stdc++6 \
  libc6-i386
msg_ok "Installed 32-bit Libraries"

msg_info "Installing SteamCMD"
# Accept Steam license non-interactively
echo steam steam/question select "I AGREE" | debconf-set-selections
echo steam steam/license note '' | debconf-set-selections
$STD apt-get install -y steamcmd
msg_ok "Installed SteamCMD"

msg_info "Installing Screen"
$STD apt-get install -y screen
msg_ok "Installed Screen"

msg_info "Creating Service User"
useradd -m -s /bin/bash pzserver
mkdir -p /opt/pzserver
chown -R pzserver:pzserver /opt/pzserver
msg_ok "Created Service User 'pzserver'"

# Prompt for build version selection
BUILD_VERSION=$(whiptail --backtitle "Proxmox VE Helper Scripts" \
  --title "Build Version Selection" \
  --menu "Select Project Zomboid Build Version to Install:" 12 60 2 \
  "41" "Build 41 (Stable - Recommended)" \
  "42" "Build 42 (Beta/Unstable)" \
  3>&1 1>&2 2>&3)

# Default to Build 41 if cancelled
if [[ -z "$BUILD_VERSION" ]]; then
  BUILD_VERSION="41"
  msg_info "No selection made, defaulting to Build 41 (Stable)"
fi

msg_info "Downloading Project Zomboid Server (Build ${BUILD_VERSION})"
if [[ "$BUILD_VERSION" == "42" ]]; then
  su - pzserver -c "/usr/games/steamcmd +force_install_dir /opt/pzserver +login anonymous +app_update 380870 -beta unstable validate +quit"
else
  su - pzserver -c "/usr/games/steamcmd +force_install_dir /opt/pzserver +login anonymous +app_update 380870 validate +quit"
fi

# Store installed build version
echo "$BUILD_VERSION" > /opt/pzserver/.pz_build_version
chown pzserver:pzserver /opt/pzserver/.pz_build_version

msg_ok "Downloaded Project Zomboid Server (Build ${BUILD_VERSION})"

msg_info "Configuring Server Directories"
# Create Zomboid directory in pzserver home for config files
mkdir -p /home/pzserver/Zomboid/Server
chown -R pzserver:pzserver /home/pzserver/Zomboid

# Create default server configuration
cat <<'EOF' > /home/pzserver/Zomboid/Server/servertest.ini
# Project Zomboid Server Configuration
# Generated by Proxmox VE Helper Scripts
# Edit this file to customize your server settings
# Documentation: https://pzwiki.net/wiki/Server_settings

# Server Identity
PublicName=My PZ Server
PublicDescription=Project Zomboid Dedicated Server

# Network Settings
Public=false
DefaultPort=16261
UDPPort=16262
MaxPlayers=16
PingLimit=400

# Server Password (leave empty for no password)
Password=

# RCON Settings (Remote Console)
RCONPort=27015
RCONPassword=

# Performance Settings
PauseEmpty=true
SpeedLimit=50
SaveWorldEveryMinutes=30

# Game Settings
Open=true
PVP=false
SpawnPoint=0,0,0

# Steam Workshop Mods
# Add Workshop item IDs separated by semicolons
# Example: WorkshopItems=1234567890;0987654321
WorkshopItems=

# Mod IDs (must match WorkshopItems order)
# Example: Mods=ModFolder1;ModFolder2
Mods=

# Map (default is Muldraugh, KY)
Map=Muldraugh, KY

# Anticheat
AntiCheatProtectionType1=true
AntiCheatProtectionType2=true
AntiCheatProtectionType3=true
AntiCheatProtectionType4=true
AntiCheatProtectionType5=true
AntiCheatProtectionType6=true
AntiCheatProtectionType7=true
AntiCheatProtectionType8=true
AntiCheatProtectionType9=true
AntiCheatProtectionType10=true
AntiCheatProtectionType11=true
AntiCheatProtectionType12=true
AntiCheatProtectionType13=true
AntiCheatProtectionType14=true
AntiCheatProtectionType15=true
AntiCheatProtectionType16=true
AntiCheatProtectionType17=true
AntiCheatProtectionType18=true
AntiCheatProtectionType19=true
AntiCheatProtectionType20=true
AntiCheatProtectionType21=true
AntiCheatProtectionType22=true
AntiCheatProtectionType23=true
AntiCheatProtectionType24=true

# Voice Chat
VoiceEnable=true
VoiceMinDistance=10.0
VoiceMaxDistance=100.0
Voice3D=true

# Player Settings
DisplayUserName=true
ShowFirstAndLastName=false
AllowCoop=true
SleepAllowed=false
SleepNeeded=false

# Loot Settings
HoursForLootRespawn=0
MaxItemsForLootRespawn=4
ConstructionPreventsLootRespawn=true

# Safety System
SafetySystem=true
ShowSafety=true
SafetyToggleTimer=2
SafetyCooldownTimer=3

# Logging
ServerPlayerID=true
EOF

chown pzserver:pzserver /home/pzserver/Zomboid/Server/servertest.ini
msg_ok "Configured Server Directories"

msg_info "Creating systemd Service"
cat <<'EOF' > /etc/systemd/system/project-zomboid-screen.service
[Unit]
Description=Project Zomboid Dedicated Server
Documentation=https://pzwiki.net/wiki/Dedicated_server
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
User=pzserver
Group=pzserver
WorkingDirectory=/opt/pzserver

# Environment
Environment="HOME=/home/pzserver"
Environment="LD_LIBRARY_PATH=/opt/pzserver/linux64:/opt/pzserver/natives"

# Start in screen session for console access
ExecStart=/usr/bin/screen -dmS pzserver /opt/pzserver/start-server.sh -servername servertest

# Graceful shutdown - send quit command to save world
ExecStop=/usr/bin/screen -p 0 -S pzserver -X stuff "quit^M"

# Restart configuration
Restart=on-failure
RestartSec=30
TimeoutStartSec=180
TimeoutStopSec=120

# Resource limits
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target
EOF
msg_ok "Created systemd Service"

msg_info "Creating Admin Setup Script"
cat <<'EOF' > /opt/pzserver/setup-admin.sh
#!/bin/bash
#
# Project Zomboid Server - Initial Setup Script
# This script helps you complete the first-time server configuration
#

echo "========================================"
echo " Project Zomboid Server - Initial Setup"
echo "========================================"
echo ""
echo "This script will start the server for initial configuration."
echo "During first run, you will be prompted to:"
echo "  1. Create an admin password"
echo ""
echo "After setup is complete:"
echo "  1. Type 'quit' in the server console to stop the server"
echo "  2. Start the server properly with: systemctl start project-zomboid-screen"
echo ""
echo "Server console commands you should know:"
echo "  - quit        : Save and stop the server"
echo "  - save        : Force a world save"
echo "  - players     : List connected players"
echo "  - adduser     : Add a new user"
echo "  - setaccesslevel <user> <level> : Set user access (admin, moderator, etc.)"
echo ""
echo "Current build version: $(cat /opt/pzserver/.pz_build_version 2>/dev/null || echo 'unknown')"
echo ""
read -p "Press Enter to start the server for initial setup..."

cd /opt/pzserver
./start-server.sh -servername servertest

echo ""
echo "========================================"
echo " Setup Complete"
echo "========================================"
echo ""
echo "If you set an admin password, you can now:"
echo "  1. Start the server: systemctl start project-zomboid-screen"
echo "  2. Enable auto-start: systemctl enable project-zomboid-screen"
echo "  3. Check status: systemctl status project-zomboid-screen"
echo "  4. Access console: screen -r pzserver (Ctrl+A, D to detach)"
echo ""
echo "Server configuration file:"
echo "  /home/pzserver/Zomboid/Server/servertest.ini"
echo ""
echo "Server logs:"
echo "  /home/pzserver/Zomboid/Logs/"
echo ""
EOF
chmod +x /opt/pzserver/setup-admin.sh
chown pzserver:pzserver /opt/pzserver/setup-admin.sh
msg_ok "Created Admin Setup Script"

msg_info "Creating Server Management Scripts"
# Create a helper script for updating the server
cat <<'EOF' > /opt/pzserver/update-server.sh
#!/bin/bash
#
# Project Zomboid Server Update Script
# Stops the server, updates via SteamCMD, and restarts
#

BUILD_VERSION=$(cat /opt/pzserver/.pz_build_version 2>/dev/null || echo "41")

echo "Current build version: $BUILD_VERSION"
echo ""
echo "Stopping server..."
systemctl stop project-zomboid-screen 2>/dev/null
sleep 5

echo "Updating server files..."
if [[ "$BUILD_VERSION" == "42" ]]; then
  /usr/games/steamcmd +force_install_dir /opt/pzserver +login anonymous +app_update 380870 -beta unstable validate +quit
else
  /usr/games/steamcmd +force_install_dir /opt/pzserver +login anonymous +app_update 380870 validate +quit
fi

echo ""
echo "Starting server..."
systemctl start project-zomboid-screen

echo ""
echo "Update complete! Check server status with: systemctl status project-zomboid-screen"
EOF
chmod +x /opt/pzserver/update-server.sh
chown pzserver:pzserver /opt/pzserver/update-server.sh

# Create a backup script
cat <<'EOF' > /opt/pzserver/backup-server.sh
#!/bin/bash
#
# Project Zomboid Server Backup Script
# Creates a timestamped backup of server data
#

BACKUP_DIR="/home/pzserver/backups"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_FILE="pz_backup_${TIMESTAMP}.tar.gz"

mkdir -p "$BACKUP_DIR"

echo "Creating backup: ${BACKUP_FILE}"
echo "This may take a few minutes..."

# Backup the Zomboid directory (saves, configs, etc.)
tar -czf "${BACKUP_DIR}/${BACKUP_FILE}" \
  -C /home/pzserver \
  Zomboid

echo ""
echo "Backup created: ${BACKUP_DIR}/${BACKUP_FILE}"
echo "Backup size: $(du -h "${BACKUP_DIR}/${BACKUP_FILE}" | cut -f1)"
echo ""
echo "To restore, stop the server and extract:"
echo "  systemctl stop project-zomboid-screen"
echo "  tar -xzf ${BACKUP_DIR}/${BACKUP_FILE} -C /home/pzserver"
echo "  systemctl start project-zomboid-screen"
EOF
chmod +x /opt/pzserver/backup-server.sh
chown pzserver:pzserver /opt/pzserver/backup-server.sh
msg_ok "Created Server Management Scripts"

msg_info "Setting Permissions"
chown -R pzserver:pzserver /opt/pzserver
chown -R pzserver:pzserver /home/pzserver
msg_ok "Set Permissions"

msg_info "Enabling Service"
systemctl daemon-reload
systemctl enable project-zomboid-screen.service
msg_ok "Enabled Service"

motd_ssh
customize

msg_info "Cleaning up"
$STD apt-get -y autoremove
$STD apt-get -y autoclean
msg_ok "Cleaned"
